### ISSUE TITLE
feat: Configure Redis for licensing server

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp-website-licensing-server#20]
# User Story 
As a developer, I want to use Redis to log requests to the licensing server so that I can rate limit and block when needed to prevent overload. 

## Acceptance Criteria
- [ ] Redis logs server requests
- [ ] Server request counts can be queried by site

**Comment by JasonTheAdams** [comment]
@mikejhale Did you mean to close this? This issue has to do with how @ravinderk would implement Redis, not Redis getting set up — looking at the acceptance criteria, anyway.
